#include "TIMER0.h"

void TIMER0_initialize(void)
{
	CLR_BIT(TCCR0,WGM00);
	SET_BIT(TCCR0,WGM01);    //CTC MODE
	
		OCR0=160;
		
		sei();
		SET_BIT(TIMSK,OCIE0);  // ENABLE CTC INTERRUPT
		
		SET_BIT(TCCR0,CS00);
		CLR_BIT(TCCR0,CS01);  //PRESCALAR 1024 AND START TIMER
 		SET_BIT(TCCR0,CS02);
		
}